version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        arch: arm64
        archImage: arm64
    ports:
      - '8080:8080'
    environment:
      AWS_PROFILE: $AWS_PROFILE
      AWS_REGION: us-east-1
    volumes:
      - $HOME/.aws:/root/.aws
